[build]
publish = "_site"
command = "./build-website.sh"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self';"

[build.environment]
  YARN_VERSION = "1.22.10"
  NODE_OPTIONS="--max-old-space-size=8192"
  BAZELISK_HOME="/opt/build/cache/bazelisk"
